#!/usr/bin/env bash

set -ex

docker build --tag 'fedora_wsl' .
docker run --name fedorawsl fedora_wsl
docker export --output=base.tar fedorawsl
docker rm -f fedorawsl

mkdir rootfs
sudo tar -xpf base.tar -C rootfs
echo "# This file was automatically generated by WSL. To stop automatic generation of this file, remove this line." | sudo tee rootfs/etc/resolv.conf
sudo chmod +x rootfs

cat <<EOF | sudo tee -a rootfs/etc/wsl.conf
[automount]

[network]

[interop]

[user]

[boot]
EOF

(
    cd rootfs
    sudo tar -zcpf ../rootfs.tar.gz `sudo ls`
)
sudo chown `id -un` rootfs.tar.gz

mkdir ziproot
wget https://github.com/yuk7/wsldl/releases/download/23051400/icons.zip
unzip icons.zip Fedora.exe
cp Fedora.exe ziproot/Fedora.exe
cp rootfs.tar.gz ziproot/

(
    cd ziproot
    zip ../Fedora.zip *
)

